version: "3.9"

services:
  server:
    build: ./DrawFigureServer
    volumes:
      - ./DrawFigureServer:/app/DrawFigureServer
      - /app/DrawFigureServer/node_modules
    ports:
      - 5000:5000


  client:
    stdin_open: true
    build: ./DrawFigureClient
    volumes:
      - ./DrawFigureClient:/app/DrawFigureClient
      - /app/DrawFigureClient/node_modules
    ports:
      - 3000:3000
    environment:
      SERVER_HOST: server
      SERVER_PORT: 5000
      WATCHPACK_POLLING: true

    depends_on:
      - server


